language: node_js

node_js:
  - 11.10.1

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s
  - export PATH=$HOME/.yarn/bin:$PATH

script:
  - yarn validate
  - yarn codecov
